# working dir
ROOT: ""
#SAVE_DIR: "/home/lixg/data/spacenet/logs_Vegas/logs_ours"
SAVE_DIR: "logs_ours"

IMAGE_PATH: "../data/images/"
LABEL_PATH: "../data/labels/"
EDGE_PATH: "../data/edge/"
REGION_PATH: "../data/region/"
DIR_PATH: "../data/direction/"
TRAIN_LIST: "../data/list/train_list.txt"
TEST_LIST: "../data/list/test_list.txt"


# training parameters
RESTORE: False 

BATCH_SIZE: 5
IMG_SIZE: 512
REGION_SIZE: 32
STEP: 100
EPOCH: 201
INTERVAL: 20
LEARNING_RATE: 0.0001
LEARNING_RATE_DECAY: 1.0
